---
- name: Upload the PowerShell script to the target machine
  ansible.builtin.template:
    src: "../data/{{ script_name }}"     # Local path to the script
    dest: "C:\\{{ script_name }}"   # Destination path on the Windows machine

- name: Run the uploaded PowerShell script
  win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File C:\{{ script_name }}
  args:
    executable: powershell.exe
  register: powershell_output

- name: Display stdout of {{ script_name }}
  ansible.builtin.debug:
    msg: "{{ powershell_output.stdout }}"

- name: Display stderr of {{ script_name }}
  ansible.builtin.debug:
    msg: "{{ powershell_output.stderr }}"
  when: powershell_output.stderr != ""

- name: Delete the PowerShell script after execution
  ansible.builtin.win_file:
    path: "C:\\{{ script_name }}"
    state: absent
