---
- name: Configure DNS to include parent dc ip 
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses:
      - "{{ parent_dc_ip }}"
      - "{{ current_host_ip }}"

- name: Create a child domain
  microsoft.ad.domain_child:
    dns_domain_name: "{{ dns_domain_name }}"
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"
    safe_mode_password: "{{ safe_mode_password }}"
    create_dns_delegation: "{{ create_dns_delegation }}"
    reboot: "{{ reboot }}"
    install_dns: "{{ install_dns }}" 
