---
- name: Upload the PowerShell script to the target machine
  ansible.builtin.template:
    src: ../data/disable_defender_gpo.ps1     # Local path to the script
    dest: C:\disable_defender_gpo.ps1   # Destination path on the Windows machine

- name: Run the uploaded PowerShell script
  win_shell: |
    powershell.exe -ExecutionPolicy Bypass -File C:\disable_defender_gpo.ps1
  args:
    executable: powershell.exe
  register: powershell_output

- name: Display stdout of disable_defender_gpo.ps1
  ansible.builtin.debug:
    msg: "{{ powershell_output.stdout }}"

- name: Display stderr of disable_defender_gpo.ps1
  ansible.builtin.debug:
    msg: "{{ powershell_output.stderr }}"
  when: powershell_output.stderr != ""

- name: Delete the PowerShell script after execution
  ansible.builtin.win_file:
    path: C:\disable_defender_gpo.ps1
    state: absent
